version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hellobuddy
      MYSQL_USER: hellobuddy
      MYSQL_PASSWORD: 4989@4989
      # MYSQL_HOST : ''
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    # command: mysql -u root --password=rootpassword hellobuddy < DATABASE_Backup.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql-data: {}

