version: '3.8'

services:

  db:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    # command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./ddata/mysql:/var/lib/mysql
    # env_file:
    #   - ./.env.dev
    environment:
      MYSQL_ROOT_PASSWORD : rootpassword
      MYSQL_USER : hellobuddy
      MYSQL_DATABASE : hellobuddy
      MYSQL_PASSWORD : 4989@4989
    # ports:
    #   - 3306:3306

  redis:
    container_name: redis-container
    image: redis:alpine
    restart: always
    # ports:
    #   - "6379:6379"

  web:
    # image: web:django
    container_name: django-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    # env_file:
    #   - ./.env.dev
    ports:
      - 8000:8000
    environment:
      DATABASE : mysql  #for entrypoint check
    depends_on:
      - db
      - redis




