# Generated by Django 3.2.13 on 2022-04-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_isavailable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='isAvailable',
        ),
    ]
